[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Handle trailing slashes consistently
[[redirects]]
  from = "/*/index.html"
  to = "/:splat/"
  status = 301

# Redirect trailing slashes to non-trailing slash for consistency
[[redirects]]
  from = "/about/"
  to = "/about"
  status = 301

[[redirects]]
  from = "/services/"
  to = "/services"
  status = 301

[[redirects]]
  from = "/portfolio/"
  to = "/portfolio"
  status = 301

[[redirects]]
  from = "/contact/"
  to = "/contact"
  status = 301

[[redirects]]
  from = "/blog/"
  to = "/blog"
  status = 301

# Fallback for SPA routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200