// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://deouutjevqsyuaqeqslf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlb3V1dGpldnFzeXVhcWVxc2xmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3OTU3NjUsImV4cCI6MjA2NTM3MTc2NX0.W6NVl94kKviPRQADcjK8j0qoSngG2bs9O5M-tO8Yg08";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);